import { Submission, Loan, SchemeRule, User, AuditLog } from '../../../shared/types';
import { DEFAULT_SCHEMES } from '../../../shared/defaultSchemes';
import { generateSimulatedPHash } from '../../../shared/fraudUtils';

export const INITIAL_SCHEMES: SchemeRule[] = [...DEFAULT_SCHEMES];

export const INITIAL_USERS: User[] = [
  {
    userId: 'user_super_admin_01',
    phone: '+919876543213',
    name: 'Dr. Aruna Roy',
    aadhaarLast4: '1102',
    role: 'superAdmin',
    district: 'State HQ',
    state: 'National',
    createdAt: '2026-01-01T08:00:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 100
  },
  {
    userId: 'user_state_officer_01',
    phone: '+919876543210',
    name: 'Anjali Deshmukh',
    aadhaarLast4: '7821',
    role: 'stateOfficer',
    district: 'Pune',
    state: 'Maharashtra',
    createdAt: '2026-01-10T10:00:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 98
  },
  {
    userId: 'user_bank_admin_01',
    phone: '+919876543211',
    name: 'Suresh Kumar',
    aadhaarLast4: '4519',
    role: 'bankAdmin',
    district: 'Pune',
    state: 'Maharashtra',
    createdAt: '2026-01-15T11:00:00Z',
    lastLogin: new Date().toISOString()
  },
  {
    userId: 'user_field_officer_01',
    phone: '+919876543212',
    name: 'Vikram Shinde',
    aadhaarLast4: '9932',
    role: 'fieldOfficer',
    district: 'Pune',
    state: 'Maharashtra',
    assignedLoans: ['loan_pune_01', 'loan_pune_03'],
    createdAt: '2026-02-01T09:00:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 94
  },
  {
    userId: 'user_field_officer_02',
    phone: '+919876543214',
    name: 'Gurpreet Singh',
    aadhaarLast4: '4419',
    role: 'fieldOfficer',
    district: 'Ludhiana',
    state: 'Punjab',
    assignedLoans: ['loan_ludhiana_05'],
    createdAt: '2026-02-10T10:00:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 96
  },
  {
    userId: 'user_field_officer_03',
    phone: '+919876543215',
    name: 'Karthik N.',
    aadhaarLast4: '8812',
    role: 'fieldOfficer',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    assignedLoans: ['loan_coimbatore_03'],
    createdAt: '2026-02-15T11:00:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 93
  },
  {
    userId: 'user_field_officer_04',
    phone: '+919876543216',
    name: 'Amitabh Joshi',
    aadhaarLast4: '3310',
    role: 'fieldOfficer',
    district: 'Ahmedabad',
    state: 'Gujarat',
    assignedLoans: ['loan_ahmedabad_06'],
    createdAt: '2026-02-18T14:00:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 95
  },
  {
    userId: 'user_ben_01',
    phone: '+919812345670',
    name: 'Ramesh Patil',
    aadhaarLast4: '3812',
    role: 'beneficiary',
    district: 'Pune',
    state: 'Maharashtra',
    createdAt: '2026-06-01T08:30:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 90
  },
  {
    userId: 'user_ben_02',
    phone: '+919812345671',
    name: 'Sunita Sharma',
    aadhaarLast4: '9120',
    role: 'beneficiary',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    createdAt: '2026-06-10T09:15:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 42
  },
  {
    userId: 'user_ben_03',
    phone: '+919812345672',
    name: 'Kavitha Raman',
    aadhaarLast4: '6610',
    role: 'beneficiary',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    createdAt: '2026-06-15T10:00:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 95
  },
  {
    userId: 'user_ben_04',
    phone: '+919812345673',
    name: 'Mahesh Meena',
    aadhaarLast4: '1194',
    role: 'beneficiary',
    district: 'Jaipur',
    state: 'Rajasthan',
    createdAt: '2026-06-20T11:45:00Z',
    lastLogin: new Date().toISOString(),
    trustScore: 35
  }
];

export const INITIAL_LOANS: Loan[] = [
  {
    loanId: 'loan_pune_01',
    beneficiaryId: 'user_ben_01',
    beneficiaryName: 'Ramesh Patil',
    beneficiaryPhone: '+91 98123 45670',
    loanAmount: 180000,
    disbursedAmount: 180000,
    schemeId: 'scheme_milch_animal',
    schemeName: 'National Livestock Mission (Dairy)',
    assetCategory: 'Milch Animal',
    bankName: 'State Bank of India',
    branchCode: 'SBI000452',
    district: 'Pune',
    state: 'Maharashtra',
    sanctionDate: '2026-07-05',
    expectedVerificationDate: '2026-08-30',
    status: 'under_review',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-09-10',
    fraudScore: 6,
    fraudFlags: [],
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z'
  },
  {
    loanId: 'loan_varanasi_02',
    beneficiaryId: 'user_ben_02',
    beneficiaryName: 'Sunita Sharma',
    beneficiaryPhone: '+91 98123 45671',
    loanAmount: 85000,
    disbursedAmount: 85000,
    schemeId: 'scheme_pmmy_sewing',
    schemeName: 'PMMY Mudra — Micro Textile & Sewing Units',
    assetCategory: 'Sewing Machine',
    bankName: 'Bank of Baroda',
    branchCode: 'BARB0VARANA',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    sanctionDate: '2026-07-12',
    expectedVerificationDate: '2026-08-25',
    status: 'flagged',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-08-31',
    fraudScore: 68,
    fraudFlags: ['METADATA_GPS_DRIFT_EXCEEDED (1420m)', 'LOCATION_OUT_OF_DISTRICT_BOUNDARY'],
    createdAt: '2026-07-12T14:00:00Z',
    updatedAt: '2026-08-12T09:30:00Z'
  },
  {
    loanId: 'loan_coimbatore_03',
    beneficiaryId: 'user_ben_03',
    beneficiaryName: 'Kavitha Raman',
    beneficiaryPhone: '+91 98123 45672',
    loanAmount: 220000,
    disbursedAmount: 220000,
    schemeId: 'scheme_pm_kusum_solar',
    schemeName: 'PM-KUSUM Solar Agriculture Water Pump',
    assetCategory: 'Solar Water Pump',
    bankName: 'Canara Bank',
    branchCode: 'CNRB000219',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    sanctionDate: '2026-07-15',
    expectedVerificationDate: '2026-08-28',
    status: 'approved',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-09-01',
    fraudScore: 2,
    fraudFlags: [],
    createdAt: '2026-07-15T11:00:00Z',
    updatedAt: '2026-08-14T16:00:00Z'
  },
  {
    loanId: 'loan_jaipur_04',
    beneficiaryId: 'user_ben_04',
    beneficiaryName: 'Mahesh Meena',
    beneficiaryPhone: '+91 98123 45673',
    loanAmount: 650000,
    disbursedAmount: 650000,
    schemeId: 'scheme_farm_mechanization',
    schemeName: 'Sub-Mission on Agricultural Mechanization (Tractor)',
    assetCategory: 'Tractor',
    bankName: 'Punjab National Bank',
    branchCode: 'PUNB001920',
    district: 'Jaipur',
    state: 'Rajasthan',
    sanctionDate: '2026-07-18',
    expectedVerificationDate: '2026-08-22',
    status: 'flagged',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-08-30',
    fraudScore: 78,
    fraudFlags: ['DUPLICATE_IMAGE_DETECTED', 'RECYCLED_ASSET_PHOTO_HASH'],
    createdAt: '2026-07-18T16:20:00Z',
    updatedAt: '2026-08-16T11:10:00Z'
  },
  {
    loanId: 'loan_ludhiana_05',
    beneficiaryId: 'user_ben_07',
    beneficiaryName: 'Harpreet Singh',
    beneficiaryPhone: '+91 98123 45676',
    loanAmount: 600000,
    disbursedAmount: 600000,
    schemeId: 'scheme_farm_mechanization',
    schemeName: 'Sub-Mission on Agricultural Mechanization (Tractor)',
    assetCategory: 'Tractor',
    bankName: 'Punjab National Bank',
    branchCode: 'PUNB004512',
    district: 'Ludhiana',
    state: 'Punjab',
    sanctionDate: '2026-08-01',
    expectedVerificationDate: '2026-09-20',
    status: 'under_review',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-10-15',
    fraudScore: 8,
    fraudFlags: [],
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-16T12:00:00Z'
  },
  {
    loanId: 'loan_ahmedabad_06',
    beneficiaryId: 'user_ben_08',
    beneficiaryName: 'Bhavik Patel',
    beneficiaryPhone: '+91 98123 45677',
    loanAmount: 320000,
    disbursedAmount: 320000,
    schemeId: 'scheme_ev_cargo_rickshaw',
    schemeName: 'PM e-Drive / FAME-II Electric Cargo Vehicle',
    assetCategory: 'Electric Cargo Vehicle',
    bankName: 'State Bank of India',
    branchCode: 'SBI007812',
    district: 'Ahmedabad',
    state: 'Gujarat',
    sanctionDate: '2026-08-05',
    expectedVerificationDate: '2026-09-25',
    status: 'approved',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-10-20',
    fraudScore: 4,
    fraudFlags: [],
    createdAt: '2026-08-05T11:00:00Z',
    updatedAt: '2026-08-18T15:00:00Z'
  },
  {
    loanId: 'loan_bengaluru_07',
    beneficiaryId: 'user_ben_09',
    beneficiaryName: 'Manjunath Gowda',
    beneficiaryPhone: '+91 98123 45678',
    loanAmount: 140000,
    disbursedAmount: 140000,
    schemeId: 'scheme_pmksy_drip',
    schemeName: 'PMKSY — Per Drop More Crop (Micro-Irrigation)',
    assetCategory: 'Drip Irrigation System',
    bankName: 'Canara Bank',
    branchCode: 'CNRB005612',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    sanctionDate: '2026-08-08',
    expectedVerificationDate: '2026-09-28',
    status: 'under_review',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-10-25',
    fraudScore: 5,
    fraudFlags: [],
    createdAt: '2026-08-08T09:30:00Z',
    updatedAt: '2026-08-17T14:00:00Z'
  },
  {
    loanId: 'loan_kamrup_08',
    beneficiaryId: 'user_ben_10',
    beneficiaryName: 'Dipankar Saikia',
    beneficiaryPhone: '+91 98123 45679',
    loanAmount: 450000,
    disbursedAmount: 450000,
    schemeId: 'scheme_pmmsy_aquaculture',
    schemeName: 'PMMSY — Pradhan Mantri Matsya Sampada Yojana',
    assetCategory: 'Fish Farming Unit',
    bankName: 'UCO Bank',
    branchCode: 'UCBA001290',
    district: 'Kamrup',
    state: 'Assam',
    sanctionDate: '2026-08-10',
    expectedVerificationDate: '2026-10-01',
    status: 'under_review',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-10-30',
    fraudScore: 7,
    fraudFlags: [],
    createdAt: '2026-08-10T10:15:00Z',
    updatedAt: '2026-08-18T16:30:00Z'
  },
  {
    loanId: 'loan_indore_09',
    beneficiaryId: 'user_ben_11',
    beneficiaryName: 'Raghuveer Yadav',
    beneficiaryPhone: '+91 98123 45680',
    loanAmount: 850000,
    disbursedAmount: 850000,
    schemeId: 'scheme_nabard_cold_storage',
    schemeName: 'NABARD Rural Infrastructure & Micro Cold Storage',
    assetCategory: 'Micro Cold Storage',
    bankName: 'Bank of India',
    branchCode: 'BKID004312',
    district: 'Indore',
    state: 'Madhya Pradesh',
    sanctionDate: '2026-08-12',
    expectedVerificationDate: '2026-10-05',
    status: 'approved',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-11-05',
    fraudScore: 3,
    fraudFlags: [],
    createdAt: '2026-08-12T11:45:00Z',
    updatedAt: '2026-08-19T10:00:00Z'
  },
  {
    loanId: 'loan_ernakulam_10',
    beneficiaryId: 'user_ben_12',
    beneficiaryName: 'Thomas Kurian',
    beneficiaryPhone: '+91 98123 45681',
    loanAmount: 480000,
    disbursedAmount: 480000,
    schemeId: 'scheme_pmmsy_aquaculture',
    schemeName: 'PMMSY — Pradhan Mantri Matsya Sampada Yojana',
    assetCategory: 'Fish Farming Unit',
    bankName: 'Federal Bank',
    branchCode: 'FDRL001923',
    district: 'Ernakulam',
    state: 'Kerala',
    sanctionDate: '2026-08-14',
    expectedVerificationDate: '2026-10-10',
    status: 'approved',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-11-10',
    fraudScore: 2,
    fraudFlags: [],
    createdAt: '2026-08-14T14:00:00Z',
    updatedAt: '2026-08-19T12:00:00Z'
  },
  {
    loanId: 'loan_khordha_11',
    beneficiaryId: 'user_ben_13',
    beneficiaryName: 'Jayanti Behera',
    beneficiaryPhone: '+91 98123 45682',
    loanAmount: 180000,
    disbursedAmount: 180000,
    schemeId: 'scheme_nbhm_honey',
    schemeName: 'National Beekeeping & Honey Mission (NBHM)',
    assetCategory: 'Beekeeping & Honey Unit',
    bankName: 'State Bank of India',
    branchCode: 'SBI003412',
    district: 'Khordha',
    state: 'Odisha',
    sanctionDate: '2026-08-15',
    expectedVerificationDate: '2026-10-15',
    status: 'under_review',
    officerAssignedId: 'user_field_officer_01',
    officerAssignedName: 'Vikram Shinde',
    verificationDeadline: '2026-11-15',
    fraudScore: 4,
    fraudFlags: [],
    createdAt: '2026-08-15T15:30:00Z',
    updatedAt: '2026-08-19T16:00:00Z'
  }
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  {
    submissionId: 'sub_001_pune',
    loanId: 'loan_pune_01',
    beneficiaryId: 'user_ben_01',
    beneficiaryName: 'Ramesh Patil',
    beneficiaryPhone: '+91 98123 45670',
    schemeId: 'scheme_milch_animal',
    schemeName: 'National Livestock Mission (Dairy)',
    assetCategory: 'Milch Animal',
    district: 'Pune',
    state: 'Maharashtra',
    assetDescription: 'Purchased 1 high-yielding Murrah Buffalo with yellow ear tag #MH-PUN-8841 from Baramati Cattle Fair.',
    assetTagId: 'QR-MILCH-8841-MH',
    vendorName: 'Baramati Agro Livestock Co-op',
    invoiceNumber: 'INV-2026-8812',
    purchaseDate: '2026-08-08',
    mediaFiles: [
      {
        id: 'med_pune_01',
        url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 18.5204,
        gpsLng: 73.8567,
        gpsAccuracy: 8,
        timestamp: '2026-08-09T08:30:00Z',
        deviceId: 'samsung-sm-a536e',
        hash: generateSimulatedPHash('pune_murrah_buffalo_front_legit_001'),
        exifData: {
          make: 'Samsung',
          model: 'SM-A536E',
          dateTimeOriginal: '2026-08-09T08:30:00Z',
          gpsLatitude: 18.5204,
          gpsLongitude: 73.8567,
          altitude: 560
        }
      },
      {
        id: 'med_pune_02',
        url: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'side',
        gpsLat: 18.5204,
        gpsLng: 73.8567,
        gpsAccuracy: 7,
        timestamp: '2026-08-09T08:32:00Z',
        deviceId: 'samsung-sm-a536e',
        hash: generateSimulatedPHash('pune_murrah_buffalo_side_legit_002')
      },
      {
        id: 'med_pune_03',
        url: 'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'tag',
        gpsLat: 18.5204,
        gpsLng: 73.8567,
        gpsAccuracy: 6,
        timestamp: '2026-08-09T08:34:00Z',
        deviceId: 'samsung-sm-a536e',
        hash: generateSimulatedPHash('pune_murrah_buffalo_tag_legit_003')
      }
    ],
    aiValidationResult: {
      confidence: 0.94,
      detectedLabels: [
        { name: 'Cow', confidence: 0.96 },
        { name: 'Bovine', confidence: 0.94 },
        { name: 'Dairy Cattle', confidence: 0.91 },
        { name: 'Farmer / Person', confidence: 0.88 },
        { name: 'Livestock', confidence: 0.95 }
      ],
      assetMatch: true,
      humanPresent: true,
      duplicateDetected: false,
      hammingDistance: 48,
      metadataIntact: true,
      locationInDistrict: true,
      contentSafe: true,
      anomalyScore: 94,
      breakdown: {
        gpsScore: 20,
        timestampScore: 15,
        uniquenessScore: 25,
        assetScore: 28,
        districtScore: 10
      },
      validatedAt: '2026-08-09T08:36:00Z',
      flags: []
    },
    submittedAt: '2026-08-09T08:35:00Z',
    syncedAt: '2026-08-09T08:35:10Z',
    isOffline: false,
    status: 'ai_passed'
  },
  {
    submissionId: 'sub_002_varanasi',
    loanId: 'loan_varanasi_02',
    beneficiaryId: 'user_ben_02',
    beneficiaryName: 'Sunita Sharma',
    beneficiaryPhone: '+91 98123 45671',
    schemeId: 'scheme_pmmy_sewing',
    schemeName: 'PMMY Mudra — Micro Textile & Sewing Units',
    assetCategory: 'Sewing Machine',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    assetDescription: 'USHA Industrial Master Stitch sewing machine installed in tailoring room.',
    vendorName: 'Banaras Sewing & Machinery Hub',
    invoiceNumber: 'BSM-9912',
    purchaseDate: '2026-08-01',
    mediaFiles: [
      {
        id: 'med_varanasi_01',
        url: 'https://images.unsplash.com/photo-1597843786411-a7fa8ad44a95?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 26.8467,
        gpsLng: 80.9462,
        gpsAccuracy: 120,
        timestamp: '2026-08-02T10:00:00Z',
        deviceId: 'redmi-note-11',
        hash: generateSimulatedPHash('sewing_machine_varanasi_drift_001'),
        exifData: {
          make: 'Xiaomi',
          model: 'Redmi Note 11',
          dateTimeOriginal: '2026-08-02T10:00:00Z',
          gpsLatitude: 25.3176,
          gpsLongitude: 82.9739
        }
      }
    ],
    aiValidationResult: {
      confidence: 0.88,
      detectedLabels: [
        { name: 'Sewing Machine', confidence: 0.91 },
        { name: 'Textile Machine', confidence: 0.86 },
        { name: 'Table', confidence: 0.80 }
      ],
      assetMatch: true,
      humanPresent: false,
      duplicateDetected: false,
      hammingDistance: 38,
      metadataIntact: false,
      metadataFlags: ['METADATA_GPS_DRIFT_EXCEEDED (1420m)', 'METADATA_LOW_GPS_ACCURACY (120m)'],
      locationInDistrict: false,
      locationDriftMeters: 1420,
      contentSafe: true,
      anomalyScore: 42,
      breakdown: {
        gpsScore: 5,
        timestampScore: 15,
        uniquenessScore: 25,
        assetScore: 24,
        districtScore: 0
      },
      validatedAt: '2026-08-02T10:05:00Z',
      flags: ['METADATA_GPS_DRIFT_EXCEEDED (1420m)', 'LOCATION_OUT_OF_DISTRICT_BOUNDARY', 'METADATA_LOW_GPS_ACCURACY']
    },
    submittedAt: '2026-08-02T10:04:00Z',
    syncedAt: '2026-08-02T10:04:30Z',
    isOffline: false,
    status: 'ai_flagged',
    officerNotes: 'GPS coordinates show Lucknow while beneficiary is registered in Varanasi district. Requires field spot audit.',
    clarifications: [
      {
        queryId: 'clar_01',
        officerId: 'user_state_officer_01',
        officerName: 'Anjali Deshmukh',
        message: 'The GPS coordinates recorded during submission do not match your Varanasi shop address. Please confirm where the equipment is installed.',
        createdAt: '2026-08-03T11:00:00Z'
      }
    ]
  },
  {
    submissionId: 'sub_003_coimbatore',
    loanId: 'loan_coimbatore_03',
    beneficiaryId: 'user_ben_03',
    beneficiaryName: 'Kavitha Raman',
    beneficiaryPhone: '+91 98123 45672',
    schemeId: 'scheme_pm_kusum_solar',
    schemeName: 'PM-KUSUM Solar Agriculture Water Pump',
    assetCategory: 'Solar Water Pump',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    assetDescription: '5HP Solar DC Submersible Water Pump with 12 Poly-Crystalline solar panels installed in agricultural field #Survey-84/2.',
    assetTagId: 'KUSUM-TN-CBE-5519',
    vendorName: 'Shakti Solar Agri Solutions',
    invoiceNumber: 'SSAS-2026-782',
    purchaseDate: '2026-08-10',
    mediaFiles: [
      {
        id: 'med_cbe_01',
        url: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 11.0168,
        gpsLng: 76.9558,
        gpsAccuracy: 5,
        timestamp: '2026-08-12T14:15:00Z',
        deviceId: 'oneplus-nord-ce2',
        hash: generateSimulatedPHash('cbe_solar_pump_valid_001'),
        exifData: {
          make: 'OnePlus',
          model: 'Nord CE 2',
          dateTimeOriginal: '2026-08-12T14:15:00Z',
          gpsLatitude: 11.0168,
          gpsLongitude: 76.9558,
          altitude: 430
        }
      }
    ],
    aiValidationResult: {
      confidence: 0.96,
      detectedLabels: [
        { name: 'Solar Panel', confidence: 0.98 },
        { name: 'Solar Energy', confidence: 0.95 },
        { name: 'Water Pump', confidence: 0.93 },
        { name: 'Irrigation Pipe', confidence: 0.89 }
      ],
      assetMatch: true,
      humanPresent: false,
      duplicateDetected: false,
      hammingDistance: 52,
      metadataIntact: true,
      locationInDistrict: true,
      contentSafe: true,
      anomalyScore: 98,
      breakdown: {
        gpsScore: 20,
        timestampScore: 15,
        uniquenessScore: 25,
        assetScore: 28,
        districtScore: 10
      },
      validatedAt: '2026-08-12T14:17:00Z',
      flags: []
    },
    submittedAt: '2026-08-12T14:16:00Z',
    syncedAt: '2026-08-12T14:16:20Z',
    isOffline: false,
    status: 'approved',
    officerDecision: 'approve',
    officerId: 'user_state_officer_01',
    officerReviewedAt: '2026-08-14T16:00:00Z',
    officerNotes: 'High quality installation. Geo-tags match farm survey record. Verified and approved for final subsidy release.'
  },
  {
    submissionId: 'sub_004_jaipur',
    loanId: 'loan_jaipur_04',
    beneficiaryId: 'user_ben_04',
    beneficiaryName: 'Mahesh Meena',
    beneficiaryPhone: '+91 98123 45673',
    schemeId: 'scheme_farm_mechanization',
    schemeName: 'Sub-Mission on Agricultural Mechanization (Tractor)',
    assetCategory: 'Tractor',
    district: 'Jaipur',
    state: 'Rajasthan',
    assetDescription: 'Mahindra 575 DI 45HP Tractor red model.',
    vendorName: 'Rajasthan Agri Tractors Pvt Ltd',
    invoiceNumber: 'RAT-2026-441',
    purchaseDate: '2026-08-05',
    mediaFiles: [
      {
        id: 'med_jaipur_01',
        url: 'https://images.unsplash.com/photo-1592878904946-b3cd8ae243d0?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 26.9124,
        gpsLng: 75.7873,
        gpsAccuracy: 15,
        timestamp: '2026-08-15T09:00:00Z',
        deviceId: 'vivo-y21',
        hash: generateSimulatedPHash('cbe_solar_pump_valid_001'),
        exifData: {
          make: 'Vivo',
          model: 'V2111',
          dateTimeOriginal: '2026-08-15T09:00:00Z',
          gpsLatitude: 26.9124,
          gpsLongitude: 75.7873
        }
      }
    ],
    aiValidationResult: {
      confidence: 0.92,
      detectedLabels: [
        { name: 'Tractor', confidence: 0.95 },
        { name: 'Agricultural Machinery', confidence: 0.91 },
        { name: 'Motor Vehicle', confidence: 0.88 }
      ],
      assetMatch: true,
      humanPresent: false,
      duplicateDetected: true,
      duplicateSubmissionId: 'sub_003_coimbatore',
      hammingDistance: 0,
      metadataIntact: true,
      locationInDistrict: true,
      contentSafe: true,
      anomalyScore: 48,
      breakdown: {
        gpsScore: 20,
        timestampScore: 15,
        uniquenessScore: 0,
        assetScore: 28,
        districtScore: 10
      },
      validatedAt: '2026-08-15T09:05:00Z',
      flags: ['DUPLICATE_IMAGE_DETECTED', 'RECYCLED_ASSET_PHOTO_HASH']
    },
    submittedAt: '2026-08-15T09:04:00Z',
    syncedAt: '2026-08-15T09:04:10Z',
    isOffline: false,
    status: 'ai_flagged',
    officerNotes: 'Perceptual hashing detected recycled image asset matching another active scheme submission. High fraud probability.'
  },
  {
    submissionId: 'sub_005_ludhiana',
    loanId: 'loan_ludhiana_05',
    beneficiaryId: 'user_ben_07',
    beneficiaryName: 'Harpreet Singh',
    beneficiaryPhone: '+91 98123 45676',
    schemeId: 'scheme_farm_mechanization',
    schemeName: 'Sub-Mission on Agricultural Mechanization (Tractor)',
    assetCategory: 'Tractor',
    district: 'Ludhiana',
    state: 'Punjab',
    assetDescription: 'Sonalika Tiger 55 HP Super Heavy Duty Tractor with GPS Tracker installed.',
    assetTagId: 'QR-TRAC-7781-PB',
    vendorName: 'Punjab Agri Machinery Corp',
    invoiceNumber: 'PAM-2026-112',
    purchaseDate: '2026-08-01',
    mediaFiles: [
      {
        id: 'med_ludhiana_01',
        url: 'https://images.unsplash.com/photo-1530267981375-f0de937f5f13?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 30.9010,
        gpsLng: 75.8573,
        gpsAccuracy: 8,
        timestamp: '2026-08-16T10:00:00Z',
        deviceId: 'oppo-a78',
        hash: generateSimulatedPHash('ludhiana_tractor_front_legit_005'),
        exifData: {
          make: 'OPPO',
          model: 'CPH2565',
          dateTimeOriginal: '2026-08-16T10:00:00Z',
          gpsLatitude: 30.9010,
          gpsLongitude: 75.8573
        }
      }
    ],
    aiValidationResult: {
      confidence: 0.96,
      detectedLabels: [
        { name: 'Tractor', confidence: 0.98 },
        { name: 'Agricultural Machinery', confidence: 0.95 },
        { name: 'Farm Implement', confidence: 0.91 }
      ],
      assetMatch: true,
      humanPresent: true,
      duplicateDetected: false,
      hammingDistance: 45,
      metadataIntact: true,
      locationInDistrict: true,
      contentSafe: true,
      anomalyScore: 92,
      breakdown: {
        gpsScore: 20,
        timestampScore: 15,
        uniquenessScore: 25,
        assetScore: 28,
        districtScore: 10
      },
      validatedAt: '2026-08-16T10:05:00Z',
      flags: []
    },
    submittedAt: '2026-08-16T10:04:00Z',
    syncedAt: '2026-08-16T10:04:10Z',
    isOffline: false,
    status: 'officer_review'
  },
  {
    submissionId: 'sub_006_ahmedabad',
    loanId: 'loan_ahmedabad_06',
    beneficiaryId: 'user_ben_08',
    beneficiaryName: 'Bhavik Patel',
    beneficiaryPhone: '+91 98123 45677',
    schemeId: 'scheme_ev_cargo_rickshaw',
    schemeName: 'PM e-Drive / FAME-II Electric Cargo Vehicle',
    assetCategory: 'Electric Cargo Vehicle',
    district: 'Ahmedabad',
    state: 'Gujarat',
    assetDescription: 'Mahindra Zor Grand Hi-Cap Electric 3-Wheeler Cargo Loader.',
    assetTagId: 'QR-EV-8841-GJ',
    vendorName: 'Gujarat EV Mobility Motors',
    invoiceNumber: 'GEV-9912',
    purchaseDate: '2026-08-05',
    mediaFiles: [
      {
        id: 'med_ahmedabad_01',
        url: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 23.0225,
        gpsLng: 72.5714,
        gpsAccuracy: 7,
        timestamp: '2026-08-17T11:00:00Z',
        deviceId: 'redmi-12',
        hash: generateSimulatedPHash('ahmedabad_ev_cargo_front_006')
      }
    ],
    aiValidationResult: {
      confidence: 0.94,
      detectedLabels: [
        { name: 'Electric Vehicle', confidence: 0.95 },
        { name: 'Three-Wheeler', confidence: 0.92 },
        { name: 'Commercial Vehicle', confidence: 0.89 }
      ],
      assetMatch: true,
      humanPresent: false,
      duplicateDetected: false,
      hammingDistance: 42,
      metadataIntact: true,
      locationInDistrict: true,
      contentSafe: true,
      anomalyScore: 94,
      breakdown: { gpsScore: 20, timestampScore: 15, uniquenessScore: 25, assetScore: 28, districtScore: 10 },
      validatedAt: '2026-08-17T11:05:00Z',
      flags: []
    },
    submittedAt: '2026-08-17T11:04:00Z',
    syncedAt: '2026-08-17T11:04:10Z',
    isOffline: false,
    status: 'officer_review'
  },
  {
    submissionId: 'sub_007_bengaluru',
    loanId: 'loan_bengaluru_07',
    beneficiaryId: 'user_ben_09',
    beneficiaryName: 'Manjunath Gowda',
    beneficiaryPhone: '+91 98123 45678',
    schemeId: 'scheme_pmksy_drip',
    schemeName: 'PMKSY — Per Drop More Crop (Micro-Irrigation)',
    assetCategory: 'Drip Irrigation System',
    district: 'Bengaluru Rural',
    state: 'Karnataka',
    assetDescription: 'Netafim 2-Acre Inline Drip Irrigation System with Sand Filter.',
    assetTagId: 'QR-DRIP-3390-KA',
    vendorName: 'Karnataka Agri-Tech Sol',
    invoiceNumber: 'KAT-2026-881',
    purchaseDate: '2026-08-08',
    mediaFiles: [
      {
        id: 'med_bengaluru_01',
        url: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 13.2285,
        gpsLng: 77.5824,
        gpsAccuracy: 6,
        timestamp: '2026-08-18T08:30:00Z',
        deviceId: 'samsung-m34',
        hash: generateSimulatedPHash('bengaluru_drip_front_007')
      }
    ],
    aiValidationResult: {
      confidence: 0.93,
      detectedLabels: [
        { name: 'Drip Irrigation', confidence: 0.94 },
        { name: 'Sprinkler', confidence: 0.88 },
        { name: 'Pipes', confidence: 0.85 }
      ],
      assetMatch: true,
      humanPresent: false,
      duplicateDetected: false,
      hammingDistance: 44,
      metadataIntact: true,
      locationInDistrict: true,
      contentSafe: true,
      anomalyScore: 91,
      breakdown: { gpsScore: 20, timestampScore: 15, uniquenessScore: 25, assetScore: 28, districtScore: 10 },
      validatedAt: '2026-08-18T08:35:00Z',
      flags: []
    },
    submittedAt: '2026-08-18T08:34:00Z',
    syncedAt: '2026-08-18T08:34:10Z',
    isOffline: false,
    status: 'officer_review'
  },
  {
    submissionId: 'sub_008_kamrup',
    loanId: 'loan_kamrup_08',
    beneficiaryId: 'user_ben_10',
    beneficiaryName: 'Dipankar Saikia',
    beneficiaryPhone: '+91 98123 45679',
    schemeId: 'scheme_pmmsy_aquaculture',
    schemeName: 'PMMSY — Pradhan Mantri Matsya Sampada Yojana',
    assetCategory: 'Fish Farming Unit',
    district: 'Kamrup',
    state: 'Assam',
    assetDescription: '4-Tank Biofloc Aquaculture Unit with 1HP Paddlewheel Aerators.',
    assetTagId: 'QR-FISH-1190-AS',
    vendorName: 'Brahmaputra Aqua Solutions',
    invoiceNumber: 'BAS-4412',
    purchaseDate: '2026-08-10',
    mediaFiles: [
      {
        id: 'med_kamrup_01',
        url: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?auto=format&fit=crop&w=800&q=80',
        type: 'photo',
        angle: 'front',
        gpsLat: 26.1445,
        gpsLng: 91.7362,
        gpsAccuracy: 9,
        timestamp: '2026-08-18T16:00:00Z',
        deviceId: 'vivo-v27',
        hash: generateSimulatedPHash('kamrup_fish_farming_008')
      }
    ],
    aiValidationResult: {
      confidence: 0.95,
      detectedLabels: [
        { name: 'Aquaculture', confidence: 0.96 },
        { name: 'Fish Farm', confidence: 0.93 },
        { name: 'Water Tank', confidence: 0.89 }
      ],
      assetMatch: true,
      humanPresent: false,
      duplicateDetected: false,
      hammingDistance: 46,
      metadataIntact: true,
      locationInDistrict: true,
      contentSafe: true,
      anomalyScore: 93,
      breakdown: { gpsScore: 20, timestampScore: 15, uniquenessScore: 25, assetScore: 28, districtScore: 10 },
      validatedAt: '2026-08-18T16:05:00Z',
      flags: []
    },
    submittedAt: '2026-08-18T16:04:00Z',
    syncedAt: '2026-08-18T16:04:10Z',
    isOffline: false,
    status: 'officer_review'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    logId: 'audit_01',
    entityType: 'submission',
    entityId: 'sub_001_pune',
    action: 'AI_VALIDATION_PASSED (Score: 94)',
    actorId: 'system_ai_pipeline',
    actorName: 'AI Engine',
    actorRole: 'superAdmin',
    timestamp: '2026-08-09T08:36:00Z',
    metadata: { score: 94, assetMatch: true }
  },
  {
    logId: 'audit_02',
    entityType: 'submission',
    entityId: 'sub_002_varanasi',
    action: 'FLAGGED_ANOMALY (GPS Drift)',
    actorId: 'system_ai_pipeline',
    actorName: 'AI Engine',
    actorRole: 'superAdmin',
    timestamp: '2026-08-02T10:05:00Z',
    metadata: { flags: ['METADATA_GPS_DRIFT_EXCEEDED (1420m)'] }
  },
  {
    logId: 'audit_03',
    entityType: 'submission',
    entityId: 'sub_003_coimbatore',
    action: 'OFFICER_APPROVED',
    actorId: 'user_state_officer_01',
    actorName: 'Anjali Deshmukh',
    actorRole: 'stateOfficer',
    timestamp: '2026-08-14T16:00:00Z',
    metadata: { decision: 'approve', notes: 'Verified installation' }
  },
  {
    logId: 'audit_04',
    entityType: 'submission',
    entityId: 'sub_004_jaipur',
    action: 'FLAGGED_DUPLICATE_IMAGE',
    actorId: 'system_ai_pipeline',
    actorName: 'AI Engine',
    actorRole: 'superAdmin',
    timestamp: '2026-08-15T09:05:00Z',
    metadata: { duplicateOf: 'sub_003_coimbatore', hammingDistance: 0 }
  }
];
