import { SchemeRule } from './types';

export const DEFAULT_SCHEMES: SchemeRule[] = [
  {
    schemeId: 'scheme_milch_animal',
    schemeName: 'National Livestock Mission (Dairy/Milch Cattle)',
    assetCategory: 'Milch Animal',
    description: 'Subsidized purchase of high-yield milch cows/buffaloes for dairy farming.',
    icon: 'cow',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: false,
    requireHumanPresence: true, // Requires farmer alongside animal
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['cow', 'cattle', 'bovine', 'dairy', 'livestock', 'bull', 'mammal', 'ox', 'calf'],
    silhouetteType: 'animal',
    minAiConfidence: 0.75,
    autoApprovalScoreThreshold: 85,
    flagThreshold: 50,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    schemeId: 'scheme_farm_mechanization',
    schemeName: 'Sub-Mission on Agricultural Mechanization (Tractor)',
    assetCategory: 'Tractor',
    description: 'Subsidized procurement of agricultural tractors and heavy field attachments.',
    icon: 'tractor',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: false,
    requireHumanPresence: false,
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['tractor', 'vehicle', 'agricultural machinery', 'motor vehicle', 'farm implement', 'wheel', 'engine'],
    silhouetteType: 'tractor',
    minAiConfidence: 0.80,
    autoApprovalScoreThreshold: 85,
    flagThreshold: 50,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    schemeId: 'scheme_pmmy_sewing',
    schemeName: 'PMMY Mudra — Micro Textile & Sewing Units',
    assetCategory: 'Sewing Machine',
    description: 'Empowerment loans for industrial sewing machines and tailoring workshops.',
    icon: 'scissors',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: false,
    requireHumanPresence: false,
    requireInvoice: true,
    requireQrTag: false,
    targetLabels: ['sewing machine', 'machine', 'apparel', 'tailor', 'textile', 'tool', 'table'],
    silhouetteType: 'machine',
    minAiConfidence: 0.70,
    autoApprovalScoreThreshold: 80,
    flagThreshold: 45,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    schemeId: 'scheme_pm_kusum_solar',
    schemeName: 'PM-KUSUM Solar Agriculture Water Pump',
    assetCategory: 'Solar Water Pump',
    description: 'Solarization of agricultural pumps and standalone solar pumps for irrigation.',
    icon: 'sun',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: true,
    requireHumanPresence: false,
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['solar panel', 'solar energy', 'water pump', 'pipe', 'irrigation', 'motor', 'pump', 'electronics'],
    silhouetteType: 'solar',
    minAiConfidence: 0.75,
    autoApprovalScoreThreshold: 85,
    flagThreshold: 50,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    schemeId: 'scheme_pmmsy_aquaculture',
    schemeName: 'PMMSY — Pradhan Mantri Matsya Sampada Yojana',
    assetCategory: 'Fish Farming Unit',
    description: 'Subsidies for intensive biofloc fish farming, RAS systems, and freshwater ponds.',
    icon: 'fish',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: true,
    requireHumanPresence: true,
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['fish', 'aquaculture', 'water tank', 'biofloc', 'pond', 'net', 'fisheries', 'aerator', 'water'],
    silhouetteType: 'fish',
    minAiConfidence: 0.75,
    autoApprovalScoreThreshold: 85,
    flagThreshold: 50,
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    schemeId: 'scheme_nbhm_honey',
    schemeName: 'National Beekeeping & Honey Mission (NBHM)',
    assetCategory: 'Beekeeping & Honey Unit',
    description: 'Financial assistance for modern bee colonies, hive boxes, and honey extraction gear.',
    icon: 'box',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: false,
    requireHumanPresence: true,
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['beehive', 'honeycomb', 'apiary', 'bee box', 'honey', 'hive', 'smoker', 'agriculture', 'wood'],
    silhouetteType: 'honey',
    minAiConfidence: 0.72,
    autoApprovalScoreThreshold: 80,
    flagThreshold: 48,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    schemeId: 'scheme_nabard_cold_storage',
    schemeName: 'NABARD Rural Infrastructure & Micro Cold Storage',
    assetCategory: 'Micro Cold Storage',
    description: 'Solar-powered micro cold storage chambers to prevent post-harvest perishable losses.',
    icon: 'warehouse',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: true,
    requireHumanPresence: false,
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['cold storage', 'warehouse', 'refrigeration', 'insulation', 'compressor', 'storage room', 'crates', 'building'],
    silhouetteType: 'warehouse',
    minAiConfidence: 0.78,
    autoApprovalScoreThreshold: 85,
    flagThreshold: 50,
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    schemeId: 'scheme_ev_cargo_rickshaw',
    schemeName: 'PM e-Drive / FAME-II Electric Cargo Vehicle',
    assetCategory: 'Electric Cargo Vehicle',
    description: 'Green mobility subsidy for electric three-wheeler loaders and urban delivery units.',
    icon: 'truck',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: false,
    requireHumanPresence: false,
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['electric vehicle', 'rickshaw', 'three-wheeler', 'auto rickshaw', 'ev', 'battery', 'cargo carrier', 'commercial vehicle'],
    silhouetteType: 'vehicle',
    minAiConfidence: 0.80,
    autoApprovalScoreThreshold: 85,
    flagThreshold: 50,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    schemeId: 'scheme_pmksy_drip',
    schemeName: 'PMKSY — Per Drop More Crop (Micro-Irrigation)',
    assetCategory: 'Drip Irrigation System',
    description: 'Subsidy for inline drip manifolds, sand-disc filtration units, and sprinkler networks.',
    icon: 'droplet',
    minPhotos: 3,
    requiredAngles: ['front', 'side', 'tag'],
    requireVideo: true,
    requireHumanPresence: false,
    requireInvoice: true,
    requireQrTag: true,
    targetLabels: ['drip irrigation', 'sprinkler', 'pipes', 'valves', 'filter unit', 'venturi', 'farm field', 'irrigation system'],
    silhouetteType: 'irrigation',
    minAiConfidence: 0.75,
    autoApprovalScoreThreshold: 85,
    flagThreshold: 50,
    createdAt: '2026-04-15T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  }
];
